/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BaguApp: typeof import('./src/components/BaguApp.vue')['default']
    BaguScanPanel: typeof import('./src/components/BaguScanPanel.vue')['default']
    BookShelf: typeof import('./src/components/BookShelf.vue')['default']
    CapsuleTag: typeof import('./src/components/CapsuleTag.vue')['default']
    CatalogModal: typeof import('./src/components/CatalogModal.vue')['default']
    ChatArchiveApp: typeof import('./src/components/ChatArchiveApp.vue')['default']
    DetailFooter: typeof import('./src/components/DetailFooter.vue')['default']
    DiaryApp: typeof import('./src/components/DiaryApp.vue')['default']
    DiaryEntryDetailPage: typeof import('./src/components/diary/DiaryEntryDetailPage.vue')['default']
    EmptyState: typeof import('./src/components/EmptyState.vue')['default']
    ExtrasApp: typeof import('./src/components/ExtrasApp.vue')['default']
    ExtrasChapterDetailPage: typeof import('./src/components/extras/ExtrasChapterDetailPage.vue')['default']
    FailedDraftList: typeof import('./src/components/FailedDraftList.vue')['default']
    FavoritesApp: typeof import('./src/components/FavoritesApp.vue')['default']
    FloatingBall: typeof import('./src/components/FloatingBall.vue')['default']
    ForumApp: typeof import('./src/components/ForumApp.vue')['default']
    FrontendFrame: typeof import('./src/components/FrontendFrame.vue')['default']
    GenerationPanel: typeof import('./src/components/GenerationPanel.vue')['default']
    GenerationPreviewPanel: typeof import('./src/components/GenerationPreviewPanel.vue')['default']
    GenerationSourceFields: typeof import('./src/components/GenerationSourceFields.vue')['default']
    GenerationTaskCenter: typeof import('./src/components/GenerationTaskCenter.vue')['default']
    InfoHint: typeof import('./src/components/InfoHint.vue')['default']
    LettersApp: typeof import('./src/components/LettersApp.vue')['default']
    LettersEntryDetailPage: typeof import('./src/components/letters/LettersEntryDetailPage.vue')['default']
    PhoneOverlay: typeof import('./src/components/PhoneOverlay.vue')['default']
    PreviewDraftNotice: typeof import('./src/components/PreviewDraftNotice.vue')['default']
    ProfileEntryPicker: typeof import('./src/components/ProfileEntryPicker.vue')['default']
    PromptsApp: typeof import('./src/components/PromptsApp.vue')['default']
    RawOutputEditor: typeof import('./src/components/RawOutputEditor.vue')['default']
    ReaderApp: typeof import('./src/components/ReaderApp.vue')['default']
    ReaderContent: typeof import('./src/components/ReaderContent.vue')['default']
    ReaderDetailShell: typeof import('./src/components/ReaderDetailShell.vue')['default']
    ReferencePicker: typeof import('./src/components/ReferencePicker.vue')['default']
    SearchableCombobox: typeof import('./src/components/SearchableCombobox.vue')['default']
    SearchableSelectOverlay: typeof import('./src/components/SearchableSelectOverlay.vue')['default']
    SettingsApp: typeof import('./src/components/SettingsApp.vue')['default']
    StatsApp: typeof import('./src/components/StatsApp.vue')['default']
    SummaryApp: typeof import('./src/components/SummaryApp.vue')['default']
    SummaryEntryDetailPage: typeof import('./src/components/summary/SummaryEntryDetailPage.vue')['default']
    TavernPromptCapture: typeof import('./src/components/TavernPromptCapture.vue')['default']
    TheaterApp: typeof import('./src/components/TheaterApp.vue')['default']
  }
}
