/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ActionMenu: typeof import('./src/components/ActionMenu.vue')['default']
    AppIcon: typeof import('./src/components/AppIcon.vue')['default']
    BaguDetailPage: typeof import('./src/components/BaguDetailPage.vue')['default']
    BaguHitDetailsModal: typeof import('./src/components/BaguHitDetailsModal.vue')['default']
    BaguScanPanel: typeof import('./src/components/BaguScanPanel.vue')['default']
    BatchGenerationPreviewPage: typeof import('./src/components/BatchGenerationPreviewPage.vue')['default']
    BookShelf: typeof import('./src/components/BookShelf.vue')['default']
    BulkSelectionBar: typeof import('./src/components/BulkSelectionBar.vue')['default']
    BulkSelectionCheckbox: typeof import('./src/components/BulkSelectionCheckbox.vue')['default']
    CapsuleTag: typeof import('./src/components/CapsuleTag.vue')['default']
    CatalogModal: typeof import('./src/components/CatalogModal.vue')['default']
    ConfigurationRecoveryNotice: typeof import('./src/components/ConfigurationRecoveryNotice.vue')['default']
    ContentConversionPanel: typeof import('./src/components/ContentConversionPanel.vue')['default']
    ContentVersionBadge: typeof import('./src/components/ContentVersionBadge.vue')['default']
    CreationModeModal: typeof import('./src/components/CreationModeModal.vue')['default']
    DetailFooter: typeof import('./src/components/DetailFooter.vue')['default']
    EmptyState: typeof import('./src/components/EmptyState.vue')['default']
    ExternalProfileReferencePicker: typeof import('./src/components/ExternalProfileReferencePicker.vue')['default']
    FailedDraftList: typeof import('./src/components/FailedDraftList.vue')['default']
    FailedDraftRepairPage: typeof import('./src/components/FailedDraftRepairPage.vue')['default']
    FloatingBall: typeof import('./src/components/FloatingBall.vue')['default']
    FrontendFrame: typeof import('./src/components/FrontendFrame.vue')['default']
    GenerationFormPage: typeof import('./src/components/GenerationFormPage.vue')['default']
    GenerationPanel: typeof import('./src/components/GenerationPanel.vue')['default']
    GenerationPreviewPage: typeof import('./src/components/GenerationPreviewPage.vue')['default']
    GenerationPreviewPanel: typeof import('./src/components/GenerationPreviewPanel.vue')['default']
    GenerationProviderFields: typeof import('./src/components/GenerationProviderFields.vue')['default']
    GenerationSourceFields: typeof import('./src/components/GenerationSourceFields.vue')['default']
    GenerationTaskCenter: typeof import('./src/components/GenerationTaskCenter.vue')['default']
    HomeActivityPage: typeof import('./src/components/home/HomeActivityPage.vue')['default']
    HomeContextBar: typeof import('./src/components/home/HomeContextBar.vue')['default']
    InfoHint: typeof import('./src/components/InfoHint.vue')['default']
    ItemTransferExportButton: typeof import('./src/components/ItemTransferExportButton.vue')['default']
    ItemTransferImportAction: typeof import('./src/components/ItemTransferImportAction.vue')['default']
    ItemTransferImportModal: typeof import('./src/components/ItemTransferImportModal.vue')['default']
    PhoneHome: typeof import('./src/components/PhoneHome.vue')['default']
    PhoneOverlay: typeof import('./src/components/PhoneOverlay.vue')['default']
    PreviewDraftNotice: typeof import('./src/components/PreviewDraftNotice.vue')['default']
    RawOutputEditor: typeof import('./src/components/RawOutputEditor.vue')['default']
    ReaderContent: typeof import('./src/components/ReaderContent.vue')['default']
    ReaderDetailShell: typeof import('./src/components/ReaderDetailShell.vue')['default']
    ReasoningDisclosure: typeof import('./src/components/ReasoningDisclosure.vue')['default']
    ReferencePicker: typeof import('./src/components/ReferencePicker.vue')['default']
    SearchableCombobox: typeof import('./src/components/SearchableCombobox.vue')['default']
    SearchableSelectOverlay: typeof import('./src/components/SearchableSelectOverlay.vue')['default']
    StepperControl: typeof import('./src/components/StepperControl.vue')['default']
    TavernPromptCapture: typeof import('./src/components/TavernPromptCapture.vue')['default']
    TheaterTypeGroupField: typeof import('./src/components/prompts/TheaterTypeGroupField.vue')['default']
    VersionNavigator: typeof import('./src/components/VersionNavigator.vue')['default']
  }
}
