export type VisualScenarioGroup = {
  id: string;
  scenarios: string[];
};

export function createVisualScenarioGroups(rootAppScenarios: string[]): VisualScenarioGroup[] {
  return [
    {
      id: 'shell',
      scenarios: [
        'home',
        'home-five-columns',
        'home-layout-drag',
        'home-layout-drag-dark',
        'home-tasks',
        'home-tasks-dark',
        ...rootAppScenarios,
      ],
    },
    {
      id: 'generation',
      scenarios: [
        'generation-rewrite-replay',
        'generation-preview-long-title',
        'generation-preview-long-title-edit',
        'generation-preview-long-title-raw',
        'preview-session-navigation',
        'generation-connection-override',
        'preview-draft-deferred-save',
        'preview-draft-deferred-save-dark',
      ],
    },
    { id: 'migration', scenarios: ['legacy-data-migrations', 'app-deferred-mount-order'] },
    {
      id: 'games',
      scenarios: [
        'game-guess-number-input',
        'game-2048-play',
        'game-snake-play',
        'game-minesweeper-play',
        'game-sudoku-play',
        'game-nonogram-play',
        'game-sliding-puzzle-play',
        'game-guess-number-play',
        'game-gomoku-play',
        'game-reversi-play',
        'game-solitaire-play',
      ],
    },
    {
      id: 'custom-app',
      scenarios: [
        'custom-app-conversion',
        'custom-app-conversion-complete',
        'custom-app-conversion-merge',
        'custom-app-conversion-profiles',
        'custom-app-conversion-profiles-dark',
        'custom-app-extract-rules',
        'custom-app-save-flow',
        'custom-app-definition-crud',
        'custom-app-generation-background',
        'content-transfer-dialog',
      ],
    },
    {
      id: 'converter',
      scenarios: ['content-converter-source', 'content-converter-target', 'content-converter-complete'],
    },
    { id: 'chat-insert', scenarios: ['chat-insert-operations'] },
    {
      id: 'card-writer',
      scenarios: [
        'card-writer-generation-background',
        'card-writer-saved-preview',
        'card-writer-reasoning-modal',
        'card-writer-profile-mapping-import',
        'card-writer-profile-mapping-import-dark',
      ],
    },
    { id: 'archive', scenarios: ['archive-owner-list', 'archive-current-browser', 'archive-floor-backup'] },
    {
      id: 'recovery',
      scenarios: [
        'recovery-home',
        'recovery-shelf',
        'recovery-group',
        'recovery-cleanup',
        'recovery-duplicates',
        'recovery-reader',
        'recovery-confirm',
        'recovery-result',
        'recovery-settings',
        'recovery-settings-duplicates',
      ],
    },
    {
      id: 'bagu',
      scenarios: ['bagu-scan-actions', 'bagu-hit-details', 'bagu-scan-applied', 'bagu-delete-confirm'],
    },
    {
      id: 'settings',
      scenarios: [
        'settings',
        'settings-data-management',
        'settings-data-management-dark',
        'settings-interface',
        'settings-reader-font',
        'settings-theme-persistence',
        'settings-connection',
        'settings-connection-external',
        'settings-connection-dark',
        'settings-advanced',
        'theme-form-control-isolation',
        'theme-home-icon-assets',
      ],
    },
    { id: 'mvu', scenarios: ['mvu-modifier-tree', 'mvu-modifier-crud'] },
    { id: 'status-display', scenarios: ['status-display-mvu', 'status-display-regex'] },
    { id: 'regex-display', scenarios: ['regex-display-preview', 'regex-display-crud'] },
    { id: 'regex-wizard', scenarios: ['regex-wizard-fields', 'regex-wizard-test', 'regex-wizard-save'] },
    {
      id: 'storylines',
      scenarios: [
        'storylines-detail',
        'storylines-editor',
        'storylines-profile-reference',
        'storylines-profile-reference-dark',
        'storylines-generation-background',
        'storylines-generation-failed-background',
        'storylines-failed-draft-reparse',
      ],
    },
    { id: 'scene-planner', scenarios: ['scene-planner-generation-background', 'scene-planner-history'] },
    {
      id: 'entry-library',
      scenarios: [
        'entry-library-action-menu',
        'entry-library-manual-create',
        'entry-library-item-editor',
        'entry-library-bindings',
        'entry-library-collect-manual-dedupe',
        'entry-library-collect-worldbook',
        'entry-library-ordering',
        'entry-library-scroll-return',
      ],
    },
    {
      id: 'world-slots',
      scenarios: [
        'world-slots-batch-import',
        'world-slots-entry-library',
        'world-slots-profile-reference-warning-dark',
        'world-slots-root-cleanup',
        'world-slots-root-cleanup-dark',
      ],
    },
    {
      id: 'worldbook',
      scenarios: [
        'worldbook-link-legacy-entry',
        'worldbook-entry-editor',
        'worldbook-entry-copy',
        'worldbook-entry-copy-dark',
        'world-strategy-lamps',
      ],
    },
    {
      id: 'forum',
      scenarios: [
        'forum-generate-thread',
        'forum-type-prompt',
        'forum-catalog',
        'forum-board',
        'forum-board-editor',
        'forum-bagu',
        'forum-failed-draft',
        'forum-failed-draft-reparse',
        'forum-thread',
        'forum-thread-editor',
        'forum-generate-replies',
        'forum-preview',
        'forum-thread-versions',
        'forum-version-interactions',
        'forum-rewrite-generate',
      ],
    },
    {
      id: 'preset-manager',
      scenarios: [
        'preset-builtin-diary',
        'plugin-preset-lifecycle',
        'plugin-preset-visibility',
        'preset-owner-current',
        'preset-owner-history',
        'preset-detail',
        'preset-copy-reorder',
        'preset-copy-editor',
        'preset-editor',
        'preset-editor-role-save',
        'preset-scroll-return',
        'preset-scroll-return-dark',
        'preset-move-tavern-to-plugin',
        'preset-move-plugin-to-tavern',
        'preset-move-conflict',
        'preset-move-target-failure',
        'preset-move-verify-rollback',
        'preset-move-source-delete-failure',
      ],
    },
    { id: 'preset-link', scenarios: ['preset-link-dark'] },
    { id: 'macro-builder', scenarios: ['macro-builder-dark'] },
    {
      id: 'management-tools',
      scenarios: ['script-manager', 'script-manager-dark', 'extension-transfer', 'extension-transfer-import-dark'],
    },
    {
      id: 'reader',
      scenarios: [
        'reader-detail',
        'reader-reasoning',
        'reader-swipe-candidates',
        'reader-theme-appearance',
        'reader-catalog',
        'reader-footer-persistence',
        'searchable-select',
        'searchable-select-dark-long',
      ],
    },
    {
      id: 'diary',
      scenarios: [
        'diary-batch',
        'diary-creation-mode',
        'diary-book',
        'diary-entry-editor',
        'diary-entry-editor-dark',
        'diary-bagu',
        'diary-generate',
        'diary-preview',
        'diary-failed-draft',
        'diary-failed-draft-reparse',
        'diary-entry-detail',
      ],
    },
    {
      id: 'digest',
      scenarios: ['digest-editor', 'digest-generation-background', 'digest-failed-draft-reparse'],
    },
    {
      id: 'relationship',
      scenarios: [
        'relationship-generation-background',
        'relationship-crud',
        'relationship-profile-reference',
        'relationship-profile-reference-dark',
      ],
    },
    { id: 'timekeeper', scenarios: ['timekeeper-profile-sync', 'timekeeper-profile-sync-dark'] },
    { id: 'file-repository', scenarios: ['file-repository-operations'] },
    {
      id: 'extras',
      scenarios: [
        'extras-book-generate',
        'extras-summary-rule-select',
        'extras-chapter-preview-summary',
        'extras-book-name-fallback',
        'extras-summary-overview',
        'extras-summary-generate',
        'extras-chapter-detail',
        'version-navigator-stepper',
        'content-versions',
        'content-version-interactions',
        'content-version-deletion',
        'extras-chapter-editor',
        'extras-legacy-continuation',
        'extras-continuation-references',
      ],
    },
    {
      id: 'summary',
      scenarios: [
        'summary-create',
        'summary-generate',
        'summary-preview',
        'summary-book',
        'summary-entry-detail',
        'summary-entry-editor',
        'summary-generation-background',
        'summary-bagu',
        'summary-import',
        'summary-batch',
        'content-directory-sort-persistence',
        'summary-failed-draft',
        'summary-failed-draft-reparse',
      ],
    },
    {
      id: 'prompts',
      scenarios: [
        'prompts-app-detail',
        'prompts-task-detail',
        'prompts-task-editor',
        'prompts-type-detail',
        'prompts-type-editor',
        'prompts-output-list',
        'prompts-output-editor',
        'prompts-group-editor',
        'prompts-phrase-editor',
        'prompts-template-editor',
        'prompts-phrase-list',
        'prompts-template-list',
        'prompts-library-crud',
        'prompts-config-save',
        'prompts-type-group-batch',
      ],
    },
    {
      id: 'theater',
      scenarios: [
        'theater-generate',
        'theater-generation-background',
        'theater-source-range',
        'theater-rewrite-generate',
        'theater-generate-dark-inputs',
        'theater-editor',
        'theater-frontend-footer',
        'theater-history',
        'theater-catalog-transfer',
        'theater-type-group',
        'theater-random-type',
        'theater-type-prompt-session',
        'theater-failed-draft',
      ],
    },
    {
      id: 'letters',
      scenarios: [
        'letters-entry-detail',
        'letters-book',
        'letters-entry-editor',
        'letters-bagu',
        'letters-generate',
        'letters-preview',
        'letters-failed-draft',
        'letters-failed-draft-reparse',
        'letters-rewrite-generate',
      ],
    },
    {
      id: 'tutorial',
      scenarios: [
        'tutorial-article',
        'tutorial-app-directory',
        'tutorial-missing-article',
        'tutorial-scroll-return',
        'tutorial-search-results',
      ],
    },
    {
      id: 'workbench',
      scenarios: ['workbench-logs', 'workbench-forum-step', 'workbench-profile-step', 'workbench-crud'],
    },
    {
      id: 'profiles',
      scenarios: [
        'profiles-external-catalog',
        'profiles-external-table',
        'profiles-external-transfer-table',
        'profiles-external-transfer-import',
        'profiles-external-transfer-row-dark',
        'profiles-external-missing',
        'profiles-external-error',
        'profiles-external-empty',
        'profiles-external-callback',
        'profiles-external-long-table',
        'profiles-external-dark',
        'profiles-external-mappings',
        'profiles-external-mapping-editor',
        'profiles-external-mapping-crud',
        'profiles-external-mapping-editor-dark',
        'profiles-external-failed-draft',
      ],
    },
  ];
}

export function flattenVisualScenarioGroups(groups: VisualScenarioGroup[]) {
  const scenarios = groups.flatMap(group => group.scenarios);
  const duplicates = scenarios.filter((name, index) => scenarios.indexOf(name) !== index);
  if (duplicates.length) throw new Error(`Duplicate visual scenarios: ${[...new Set(duplicates)].join(', ')}`);
  return scenarios;
}
