<template>
  <section class="pc-profiles-page"><article class="pc-editor-card"><span class="pc-kicker">{{ editing ? '编辑资料' : '新增资料' }}</span><h2>{{ currentTitle || '资料卡片' }}</h2><input v-model="title" class="pc-field" type="text" placeholder="标题" /><select v-model="tableId" class="pc-field pc-select" @change="$emit('change-table')"><option v-for="table in tables" :key="table.id" :value="table.id">{{ table.name }}</option></select><input v-if="summaryEnabled" v-model="summary" class="pc-field" type="text" placeholder="一句话摘要，可留空" /><input v-if="tagsEnabled" v-model="tagsText" class="pc-field" type="text" placeholder="标签，用逗号分隔" /><template v-for="column in columns" :key="column.id"><label class="pc-field-group"><span>{{ column.label }}</span><textarea v-if="column.type === 'textarea'" v-model="fields[column.id]" class="pc-area compact"></textarea><select v-else-if="column.type === 'select' || column.type === 'boolean'" v-model="fields[column.id]" class="pc-field pc-select"><option value="">未填写</option><option v-for="option in column.type === 'boolean' ? booleanOptions : column.options" :key="option" :value="option">{{ option }}</option></select><input v-else v-model="fields[column.id]" class="pc-field" type="text" :placeholder="column.type === 'tags' ? '用逗号分隔' : '可留空'" /></label></template><div class="pc-form-actions"><button class="pc-soft-btn" type="button" @click="$emit('back')">取消</button><button class="pc-primary-btn" type="button" @click="$emit('save')">保存</button></div></article></section>
</template>
<script setup lang="ts">
import type { ProfileTable, ProfileTableColumn } from '../store';
defineProps<{ booleanOptions: string[]; columns: ProfileTableColumn[]; currentTitle: string; editing: boolean; summaryEnabled: boolean; tables: ProfileTable[]; tagsEnabled: boolean }>();
const fields = defineModel<Record<string, string>>('fields', { required: true }); const summary = defineModel<string>('summary', { required: true }); const tableId = defineModel<string>('tableId', { required: true }); const tagsText = defineModel<string>('tagsText', { required: true }); const title = defineModel<string>('title', { required: true });
defineEmits<{ back: []; 'change-table': []; save: [] }>();
</script>
<style scoped>.pc-profiles-page { display: grid; min-height: 100%; align-content: start; gap: 14px; }</style>
