import type { Settings } from '@/type/settings';

export type VisualTheme = Settings['visualTheme'];
export type RadiusKey = 'cardRadius' | 'controlRadius' | 'iconRadius';
export type ColorKey = keyof Pick<
  VisualTheme,
  | 'accentColor'
  | 'appIconBackgroundColor'
  | 'appIconColor'
  | 'backgroundColor'
  | 'dockColor'
  | 'readerTextColor'
  | 'surfaceColor'
>;
export type IconStyleId = 'native' | 'soft' | 'unified';

export interface ThemePreset extends Omit<
  VisualTheme,
  'appAccentOverrides' | 'appIconAssetIds' | 'appIconOverrides' | 'readerTextColor'
> {
  id: string;
  mode: Settings['theme'];
  name: string;
  readerTextColor?: string;
}

export interface ThemePack {
  dark: ThemePreset;
  description: string;
  iconStyle: IconStyleId;
  id: string;
  light: ThemePreset;
  name: string;
}

export interface BuiltinIconPack {
  description: string;
  icons: Record<string, string>;
  id: string;
  name: string;
  previewIcons: string[];
}

const themePresets: ThemePreset[] = [
  {
    id: 'clear',
    name: 'A4 白纸',
    mode: 'light',
    accentColor: '#007aff',
    appIconBackgroundColor: '#ffffff',
    appIconColor: '',
    backgroundColor: '#f2f2f7',
    borderColor: 'rgba(28, 28, 30, 0.08)',
    cardRadius: 8,
    controlRadius: 8,
    dangerColor: '#ff5a5f',
    dockActiveColor: '#007aff',
    dockColor: 'rgba(255, 255, 255, 0.82)',
    hintColor: '#2d9cdb',
    iconRadius: 8,
    mutedTextColor: '#6d6d74',
    paperTextureId: 'a4',
    primaryTextColor: '#ffffff',
    softButtonColor: 'rgba(255, 255, 255, 0.96)',
    surfaceColor: 'rgba(255, 255, 255, 0.82)',
    surfaceStrongColor: 'rgba(255, 255, 255, 0.96)',
    textColor: '#1c1c1e',
  },
  {
    id: 'soft',
    name: '羊皮纸',
    mode: 'light',
    accentColor: '#ef476f',
    appIconBackgroundColor: '#fff8fa',
    appIconColor: '',
    backgroundColor: '#f4ead3',
    borderColor: 'rgba(160, 45, 78, 0.12)',
    cardRadius: 8,
    controlRadius: 8,
    dangerColor: '#e0314f',
    dockActiveColor: '#ef476f',
    dockColor: 'rgba(255, 246, 249, 0.86)',
    hintColor: '#b846d6',
    iconRadius: 8,
    mutedTextColor: '#7d5964',
    paperTextureId: 'parchment',
    primaryTextColor: '#ffffff',
    softButtonColor: 'rgba(255, 248, 250, 0.98)',
    surfaceColor: 'rgba(255, 249, 251, 0.84)',
    surfaceStrongColor: 'rgba(255, 255, 255, 0.98)',
    textColor: '#2b171d',
  },
  {
    id: 'mint',
    name: '宣纸',
    mode: 'light',
    accentColor: '#2a9d8f',
    appIconBackgroundColor: '#f8fffd',
    appIconColor: '',
    backgroundColor: '#f2f0e8',
    borderColor: 'rgba(28, 102, 94, 0.13)',
    cardRadius: 8,
    controlRadius: 8,
    dangerColor: '#d94f62',
    dockActiveColor: '#2a9d8f',
    dockColor: 'rgba(246, 255, 252, 0.86)',
    hintColor: '#268bd2',
    iconRadius: 8,
    mutedTextColor: '#526b68',
    paperTextureId: 'xuan',
    primaryTextColor: '#ffffff',
    softButtonColor: 'rgba(248, 255, 253, 0.98)',
    surfaceColor: 'rgba(248, 255, 253, 0.84)',
    surfaceStrongColor: 'rgba(255, 255, 255, 0.98)',
    textColor: '#142421',
  },
  {
    id: 'midnight',
    name: '午夜',
    mode: 'dark',
    accentColor: '#a78bfa',
    appIconBackgroundColor: 'rgba(255, 255, 255, 0.12)',
    appIconColor: '',
    backgroundColor: '#17151d',
    borderColor: 'rgba(237, 233, 254, 0.12)',
    cardRadius: 20,
    controlRadius: 16,
    dangerColor: '#ff6b81',
    dockActiveColor: '#c4b5fd',
    dockColor: 'rgba(38, 34, 48, 0.84)',
    hintColor: '#67d4ff',
    iconRadius: 14,
    mutedTextColor: '#b8b1c4',
    paperTextureId: 'cardstock',
    primaryTextColor: '#17151d',
    softButtonColor: 'rgba(255, 255, 255, 0.12)',
    surfaceColor: 'rgba(255, 255, 255, 0.07)',
    surfaceStrongColor: 'rgba(255, 255, 255, 0.12)',
    textColor: '#f7f5fa',
  },
  {
    id: 'ocean',
    name: '深海卡纸',
    mode: 'dark',
    accentColor: '#38bdf8',
    appIconBackgroundColor: 'rgba(56, 189, 248, 0.12)',
    appIconColor: '',
    backgroundColor: '#071923',
    borderColor: 'rgba(186, 230, 253, 0.12)',
    cardRadius: 18,
    controlRadius: 14,
    dangerColor: '#fb7185',
    dockActiveColor: '#38bdf8',
    dockColor: 'rgba(12, 39, 52, 0.88)',
    hintColor: '#22d3ee',
    iconRadius: 12,
    mutedTextColor: '#9fb8c4',
    paperTextureId: 'ocean',
    primaryTextColor: '#06202d',
    softButtonColor: 'rgba(186, 230, 253, 0.11)',
    surfaceColor: 'rgba(186, 230, 253, 0.07)',
    surfaceStrongColor: 'rgba(186, 230, 253, 0.11)',
    textColor: '#edfaff',
  },
  {
    id: 'graphite',
    name: '石墨黑纸',
    mode: 'dark',
    accentColor: '#f5b942',
    appIconBackgroundColor: 'rgba(255, 255, 255, 0.11)',
    appIconColor: '',
    backgroundColor: '#18191b',
    borderColor: 'rgba(255, 255, 255, 0.1)',
    cardRadius: 8,
    controlRadius: 8,
    dangerColor: '#ff6b6b',
    dockActiveColor: '#f5b942',
    dockColor: 'rgba(38, 39, 42, 0.9)',
    hintColor: '#66c7f2',
    iconRadius: 8,
    mutedTextColor: '#a9aaad',
    paperTextureId: 'graphite',
    primaryTextColor: '#1a1b1d',
    softButtonColor: 'rgba(255, 255, 255, 0.1)',
    surfaceColor: 'rgba(255, 255, 255, 0.06)',
    surfaceStrongColor: 'rgba(255, 255, 255, 0.1)',
    textColor: '#f5f5f5',
  },
  {
    id: 'velvet',
    name: '暗红皮革',
    mode: 'dark',
    accentColor: '#d6a85f',
    appIconBackgroundColor: 'rgba(214, 168, 95, 0.11)',
    appIconColor: '',
    backgroundColor: '#25131f',
    borderColor: 'rgba(236, 199, 137, 0.16)',
    cardRadius: 8,
    controlRadius: 8,
    dangerColor: '#fb7185',
    dockActiveColor: '#e3bd78',
    dockColor: 'rgba(59, 24, 43, 0.9)',
    hintColor: '#d6a85f',
    iconRadius: 8,
    mutedTextColor: '#cbb6b5',
    paperTextureId: 'velvet',
    primaryTextColor: '#2a1321',
    softButtonColor: 'rgba(236, 199, 137, 0.12)',
    surfaceColor: 'rgba(69, 31, 50, 0.76)',
    surfaceStrongColor: 'rgba(78, 36, 56, 0.94)',
    textColor: '#fff5e8',
  },
  {
    id: 'cypress',
    name: '青岚',
    mode: 'dark',
    accentColor: '#34d399',
    appIconBackgroundColor: 'rgba(209, 250, 229, 0.11)',
    appIconColor: '',
    backgroundColor: '#10241f',
    borderColor: 'rgba(209, 250, 229, 0.12)',
    cardRadius: 18,
    controlRadius: 14,
    dangerColor: '#fb7185',
    dockActiveColor: '#6ee7b7',
    dockColor: 'rgba(19, 55, 45, 0.88)',
    hintColor: '#67e8f9',
    iconRadius: 12,
    mutedTextColor: '#a7c6bb',
    paperTextureId: 'cypress',
    primaryTextColor: '#102820',
    softButtonColor: 'rgba(209, 250, 229, 0.11)',
    surfaceColor: 'rgba(209, 250, 229, 0.07)',
    surfaceStrongColor: 'rgba(209, 250, 229, 0.11)',
    textColor: '#effff8',
  },
  {
    id: 'sky',
    name: '彩色纸页',
    mode: 'light',
    accentColor: '#0284c7',
    appIconBackgroundColor: '#f7fcff',
    appIconColor: '',
    backgroundColor: '#eaf6ff',
    borderColor: 'rgba(2, 132, 199, 0.12)',
    cardRadius: 8,
    controlRadius: 8,
    dangerColor: '#e4546f',
    dockActiveColor: '#0284c7',
    dockColor: 'rgba(248, 253, 255, 0.88)',
    hintColor: '#0ea5e9',
    iconRadius: 8,
    mutedTextColor: '#577181',
    paperTextureId: 'sky',
    primaryTextColor: '#ffffff',
    softButtonColor: 'rgba(248, 253, 255, 0.9)',
    surfaceColor: 'rgba(243, 250, 255, 0.78)',
    surfaceStrongColor: 'rgba(249, 253, 255, 0.92)',
    textColor: '#102634',
  },
];

const themePresetById = new Map(themePresets.map(preset => [preset.id, preset]));
const getThemePreset = (id: string) => themePresetById.get(id)!;
export const themePacks: ThemePack[] = [
  {
    id: 'clear-night',
    name: '现代纸页',
    description: 'A4 白纸，石墨黑纸',
    iconStyle: 'soft',
    light: getThemePreset('clear'),
    dark: getThemePreset('graphite'),
  },
  {
    id: 'rose-velvet',
    name: '旧札纸页',
    description: '羊皮纸，暗红皮革',
    iconStyle: 'soft',
    light: getThemePreset('soft'),
    dark: getThemePreset('velvet'),
  },
  {
    id: 'mint-cypress',
    name: '水墨纸页',
    description: '宣纸，松柏夜墨',
    iconStyle: 'unified',
    light: getThemePreset('mint'),
    dark: getThemePreset('cypress'),
  },
  {
    id: 'sky-ocean',
    name: '彩色纸页',
    description: '彩色纸页，深海卡纸',
    iconStyle: 'unified',
    light: getThemePreset('sky'),
    dark: getThemePreset('ocean'),
  },
];

export const fontOptions = [
  { label: '系统默认', value: '' },
  { label: '苹方 / 系统黑体', value: '-apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif' },
  { label: '思源黑体', value: '"Noto Sans SC", sans-serif' },
  { label: '宋体', value: 'SimSun, "Songti SC", serif' },
  { label: '楷体', value: 'KaiTi, "Kaiti SC", serif' },
];
export const iconOptions = [
  'fa-note-sticky',
  'fa-book',
  'fa-feather-pointed',
  'fa-comments',
  'fa-masks-theater',
  'fa-envelope-open-text',
  'fa-bookmark',
  'fa-wand-magic-sparkles',
  'fa-chart-column',
  'fa-folder-open',
  'fa-glasses',
  'fa-sliders',
  'fa-diagram-project',
  'fa-address-card',
  'fa-code',
  'fa-image',
  'fa-photo-film',
  'fa-highlighter',
  'fa-clock',
  'fa-calendar-days',
  'fa-heart',
  'fa-star',
  'fa-user',
  'fa-users',
  'fa-house',
  'fa-pen',
  'fa-scroll',
  'fa-music',
  'fa-video',
  'fa-camera-retro',
  'fa-plus',
  'fa-palette',
];
export const iconStyleOptions: { id: IconStyleId; name: string }[] = [
  { id: 'native', name: '跟随 App' },
  { id: 'soft', name: '柔和底色' },
  { id: 'unified', name: '统一色' },
];
export const builtinIconPacks: BuiltinIconPack[] = [
  {
    id: 'native',
    name: '原生',
    description: '恢复每个 App 的默认图标',
    icons: {},
    previewIcons: ['fa-house', 'fa-book', 'fa-sliders'],
  },
  {
    id: 'writing',
    name: '书写',
    description: '笔记、书页与阅读',
    icons: {
      archive: 'fa-folder-open',
      bagu: 'fa-highlighter',
      'chat-insert': 'fa-pen',
      diary: 'fa-book',
      digest: 'fa-note-sticky',
      extras: 'fa-feather-pointed',
      favorites: 'fa-bookmark',
      forum: 'fa-comments',
      'game-2048': 'fa-table-cells-large',
      'game-gomoku': 'fa-chess-board',
      'game-guess-number': 'fa-arrow-down-1-9',
      'game-minesweeper': 'fa-bomb',
      'game-nonogram': 'fa-table-cells',
      'game-reversi': 'fa-circle-half-stroke',
      'game-sliding-puzzle': 'fa-grip',
      'game-snake': 'fa-route',
      'game-solitaire': 'fa-clone',
      'game-sudoku': 'fa-border-all',
      letters: 'fa-envelope-open-text',
      'preset-manager': 'fa-wand-magic-sparkles',
      profiles: 'fa-address-card',
      prompts: 'fa-quote-left',
      reader: 'fa-glasses',
      'regex-display': 'fa-highlighter',
      relationship: 'fa-users',
      settings: 'fa-sliders',
      stats: 'fa-chart-column',
      summary: 'fa-note-sticky',
      theater: 'fa-masks-theater',
      theme: 'fa-palette',
      timekeeper: 'fa-clock',
      tutorial: 'fa-book-open',
      workbench: 'fa-pen',
      'world-slots': 'fa-book',
      'worldbook-link': 'fa-book-open-reader',
    },
    previewIcons: ['fa-feather-pointed', 'fa-book-open', 'fa-pen'],
  },
  {
    id: 'workspace',
    name: '工作台',
    description: '结构、分析与管理',
    icons: {
      archive: 'fa-folder-open',
      bagu: 'fa-filter-circle-xmark',
      'chat-insert': 'fa-plus',
      diary: 'fa-calendar-days',
      digest: 'fa-highlighter',
      extras: 'fa-file-pen',
      favorites: 'fa-star',
      forum: 'fa-table-columns',
      'game-2048': 'fa-table-cells-large',
      'game-gomoku': 'fa-chess-board',
      'game-guess-number': 'fa-arrow-down-1-9',
      'game-minesweeper': 'fa-bomb',
      'game-nonogram': 'fa-table-cells',
      'game-reversi': 'fa-circle-half-stroke',
      'game-sliding-puzzle': 'fa-grip',
      'game-snake': 'fa-route',
      'game-solitaire': 'fa-clone',
      'game-sudoku': 'fa-border-all',
      letters: 'fa-inbox',
      'preset-manager': 'fa-sliders',
      profiles: 'fa-address-card',
      prompts: 'fa-wand-magic-sparkles',
      reader: 'fa-list',
      'regex-display': 'fa-code',
      relationship: 'fa-users',
      settings: 'fa-gear',
      stats: 'fa-chart-line',
      summary: 'fa-list-check',
      theater: 'fa-clapperboard',
      theme: 'fa-palette',
      timekeeper: 'fa-calendar-days',
      tutorial: 'fa-circle-question',
      workbench: 'fa-table-columns',
      'world-slots': 'fa-table-cells-large',
      'worldbook-link': 'fa-book-open-reader',
    },
    previewIcons: ['fa-table-columns', 'fa-chart-line', 'fa-diagram-project'],
  },
  {
    id: 'media',
    name: '影像',
    description: '镜头、声音与舞台',
    icons: {
      archive: 'fa-box-archive',
      bagu: 'fa-wand-magic-sparkles',
      'chat-insert': 'fa-comment-dots',
      diary: 'fa-book-open',
      digest: 'fa-bookmark',
      extras: 'fa-scroll',
      favorites: 'fa-heart',
      forum: 'fa-comment-dots',
      'game-2048': 'fa-table-cells-large',
      'game-gomoku': 'fa-chess-board',
      'game-guess-number': 'fa-arrow-down-1-9',
      'game-minesweeper': 'fa-bomb',
      'game-nonogram': 'fa-table-cells',
      'game-reversi': 'fa-circle-half-stroke',
      'game-sliding-puzzle': 'fa-grip',
      'game-snake': 'fa-route',
      'game-solitaire': 'fa-clone',
      'game-sudoku': 'fa-border-all',
      letters: 'fa-envelope',
      'preset-manager': 'fa-sliders',
      profiles: 'fa-user',
      prompts: 'fa-wand-magic-sparkles',
      reader: 'fa-glasses',
      'regex-display': 'fa-code',
      relationship: 'fa-users',
      settings: 'fa-gear',
      stats: 'fa-chart-column',
      summary: 'fa-note-sticky',
      theater: 'fa-masks-theater',
      theme: 'fa-palette',
      timekeeper: 'fa-clock',
      tutorial: 'fa-circle-play',
      workbench: 'fa-photo-film',
      'world-slots': 'fa-images',
      'worldbook-link': 'fa-book-open-reader',
    },
    previewIcons: ['fa-camera-retro', 'fa-headphones', 'fa-clapperboard'],
  },
];
export const colorControls: { key: ColorKey; label: string }[] = [
  { key: 'accentColor', label: '强调色' },
  { key: 'backgroundColor', label: '手机背景' },
  { key: 'surfaceColor', label: '卡片背景' },
  { key: 'appIconColor', label: '图标颜色' },
  { key: 'appIconBackgroundColor', label: '图标背景' },
  { key: 'dockColor', label: 'Dock 背景' },
];
export const radiusControls: { key: RadiusKey; label: string; min: number; max: number }[] = [
  { key: 'cardRadius', label: '卡片圆角', min: 8, max: 32 },
  { key: 'controlRadius', label: '控件圆角', min: 8, max: 28 },
  { key: 'iconRadius', label: '图标圆角', min: 8, max: 24 },
];
